---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn100-ipam-on
spec:
  # Target all nodes:
  namespaceSelector: {}
  network:
    topology: Localnet
    localnet:
      # physicalNetworkName MUST match what we have in spec.desiredState.ovn.bridge-mappings[].localnet field in nncp 
      physicalNetworkName: vlan100
      role: Secondary
      vlan:
        mode: Access
        access:
          id: 100
      ipam: 
        # To make the pod obtain an IP from the cluster uncomment the latter two:
        # mode: Disabled
        mode: Enabled
        lifecycle: Persistent
      subnets: 
        - 10.2.100.0/24
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn100-ipam-off
spec:
  # Target all nodes:
  namespaceSelector: {}
  network:
    topology: Localnet
    localnet:
      # physicalNetworkName MUST match what we have in spec.desiredState.ovn.bridge-mappings[].localnet field in nncp 
      physicalNetworkName: vlan100
      role: Secondary
      vlan:
        mode: Access
        access:
          id: 100
      ipam: 
        mode: Disabled
        # Will need multus dhcp plugin, or dhclient in pod
