apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: mnp-deny-vlan100
  namespace: ns-b100
  annotations:
    k8s.v1.cni.cncf.io/policy-for: ns-b100  1 
spec:
  networkSelector:
    matchLabels:
      k8s.ovn.org/cudn-name: cudn-100
  podSelector:
    matchLabels:
      app: test-100


  policyTypes:
    - Ingress
    - Egress

  ingress: []
  egress: []
